# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version(">=1.9")

Vagrant.configure("2") do |config|
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.box = "minimal/xenial64"
  config.vm.hostname = "elastic"
  config.vm.network "forwarded_port", guest: 9200, host: 9200
  config.vm.network "private_network", ip: "192.168.56.10"

  # Configure virtual hardware
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
    # Name in VirtualBox GUI
    vb.name = "elastic"
    # Customize the amount of memory on the VM
    vb.memory = "2048"
    # Customize CPUs
    vb.cpus = 2
    # Enable host's resolver as a DNS proxy in NAT mode
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  # Do not update virtual box guest additions
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end
  
  # Provisioning
  config.vm.provision "basics", type: "shell", privileged: true, inline: <<-SHELL
    export DEBIAN_FRONTEND=noninteractive
	wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
	apt-get install -y apt-transport-https
	echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" | tee -a /etc/apt/sources.list.d/elastic-6.x.list
	apt-get update
	apt-get install -y openjdk-8-jre elasticsearch
	echo "network.host: 0.0.0.0" >> /etc/elasticsearch/elasticsearch.yml
	echo "cluster.name: elasticsearch" >> /etc/elasticsearch/elasticsearch.yml
	echo "node.name: elastic1" >> /etc/elasticsearch/elasticsearch.yml
	/bin/systemctl daemon-reload
	/bin/systemctl enable elasticsearch.service
	systemctl start elasticsearch.service
  SHELL
   
end
